name: Builds

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório principal
        uses: actions/checkout@v4
        with:
          repository: WAYDS/calculadora
          ref: develop
          path: calculadora
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Checkout do repositório de testes
        uses: actions/checkout@v4
        with:
          repository: WAYDS/calculadora.teste
          path: calculadora.teste
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: |
          dotnet restore ./calculadora/calculadora.csproj
          dotnet add ./calculadora.teste/calculadora.teste.csproj reference ./calculadora/calculadora.csproj
          dotnet restore ./calculadora.teste/calculadora.teste.csproj

      - name: Buildar projetos
        run: |
          dotnet build ./calculadora/calculadora.csproj --configuration Release --no-restore
          dotnet build ./calculadora.teste/calculadora.teste.csproj --configuration Release --no-restore

      - name: Publicar artefatos do build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ./calculadora/bin/Release/net8.0
            ./calculadora.teste/bin/Release/net8.0