name: Deploy

on:
  workflow_run:
    workflows: [Testes]
    types:
      - completed

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Baixa os artefatos do build
      - name: Baixar artefatos do build
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./

      # Faz login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Construir a imagem Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/calculadora:latest ./calculadora

      # Publica a imagem no Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/calculadora:latest