name: Merge Teste Pipeline

on:
  pull_request:
    branches:
      - main 

jobs:
  test:
    name: Teste PR
    runs-on: ubuntu-latest

    steps:
      # Baixa o repositório principal
      - name: Checkout do repositório principal
        uses: actions/checkout@v4
        with:
          repository: WAYDS/calculadora
          ref: develop
          path: calculadora
          token: ${{ secrets.ACTIONS_TOKEN }}

      # Baixa o repositório de testes
      - name: Checkout do repositório de testes
        uses: actions/checkout@v4
        with:
          repository: WAYDS/calculadora.teste
          path: calculadora.teste
          token: ${{ secrets.ACTIONS_TOKEN }}

      # Configura o .NET
      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restaura as dependências
      - name: Restaurar dependências
        run: |
          dotnet restore ./calculadora/calculadora.csproj
          dotnet add ./calculadora.teste/calculadora.teste.csproj reference ./calculadora/calculadora.csproj
          dotnet restore ./calculadora.teste/calculadora.teste.csproj

      # Builda os projetos
      - name: Buildar projetos
        run: |
          dotnet build ./calculadora/calculadora.csproj --configuration Release --no-restore
          dotnet build ./calculadora.teste/calculadora.teste.csproj --configuration Release --no-restore

      - name: Executar testes
        run: dotnet test ./calculadora.teste/bin/Release/net8.0/calculadora.teste.dll