name: Merge Teste Pipeline

on:
  pull_request:
    branches:
      - main 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Baixa o repositório principal
      - name: Checkout do repositório principal
        uses: actions/checkout@v4
        with:
          repository: WAYDS/calculadora
          ref: develop
          path: calculadora
          token: ${{ secrets.ACTIONS_TOKEN }}

      # Baixa o repositório de testes
      - name: Checkout do repositório de testes
        uses: actions/checkout@v4
        with:
          repository: WAYDS/calculadora.teste
          path: calculadora.teste
          token: ${{ secrets.ACTIONS_TOKEN }}

      # Configura o .NET
      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restaura as dependências
      - name: Restaurar dependências
        run: |
          dotnet restore ./calculadora/calculadora.csproj
          dotnet add ./calculadora.teste/calculadora.teste.csproj reference ./calculadora/calculadora.csproj
          dotnet restore ./calculadora.teste/calculadora.teste.csproj

      # Builda os projetos
      - name: Buildar projetos
        run: |
          dotnet build ./calculadora/calculadora.csproj --configuration Release --no-restore
          dotnet build ./calculadora.teste/calculadora.teste.csproj --configuration Release --no-restore

      # Publica os artefatos do build
      - name: Publicar artefatos do codigo
        uses: actions/upload-artifact@v4
        with:
          name: fonte
          path: ./calculadora

      - name: Publicar binários do projeto principal
        uses: actions/upload-artifact@v4
        with:
           name: binarios-principal
           path: ./calculadora/bin/Release/net8.0

      - name: Publicar binários do projeto de testes
        uses: actions/upload-artifact@v4
        with:
            name: binarios-teste
            path: ./calculadora.teste/bin/Release/net8.0

  teste:
    name: Testes
    runs-on: ubuntu-latest
    needs: build # Depende do job "build"

    steps:
      # Baixa os artefatos do build
      - name: Baixar artefatos do build
        uses: actions/download-artifact@v4
        with:
          name: binarios-teste
          path: ./

      # Configura o .NET
      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Executa os testes
      - name: Executar testes
        run: dotnet test ./calculadora.teste.dll --logger "trx;LogFileName=test-results.trx"

      # Publica os resultados dos testes
      - name: Publicar resultados dos testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./calculadora.teste/TestResults/*.trx