name: Pipeline para testar e publicar Docker

on:
  push:
    branches:
      - develop

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      # Baixa o repositório principal
      - name: Checkout do repositório principal ${{ secrets.ACTIONS_TOKEN }}
        uses: actions/checkout@v4
        with:
          repository: WAYDS/calculadora
          ref: develop
          path: calculadora
          token: ${{ secrets.ACTIONS_TOKEN }} # Usa o segredo da organização

      # Baixa o repositório de testes
      - name: Checkout do repositório de testes
        uses: actions/checkout@v4
        with:
          repository: WAYDS/calculadora.teste
          path: calculadora.teste
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências do projeto principal
        run: dotnet restore ./calculadora/calculadora.csproj

      - name: Adicionar referência ao projeto de testes
        run: dotnet add ./calculadora.teste/calculadora.teste.csproj reference ./calculadora/calculadora.csproj

      - name: Buildar projeto principal
        run: dotnet build ./calculadora/calculadora.csproj --configuration Release --no-restore

      - name: Restaurar dependências do projeto de testes
        run: dotnet restore ./calculadora.teste/calculadora.teste.csproj

      - name: Buildar projeto de testes
        run: dotnet build ./calculadora.teste/calculadora.teste.csproj --configuration Release --no-restore

      - name: Executar testes
        run: dotnet test ./calculadora.teste/calculadora.teste.csproj --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

      - name: Publicar resultados dos testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./calculadora.teste/TestResults/*.trx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/calculadora:latest ./calculadora

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/calculadora:latest