name: Testes

on:
  workflow_run:
    workflows: ["builds"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Baixa os artefatos do build
      - name: Baixar artefatos do build
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./

      # Configura o .NET
      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Executa os testes
      - name: Executar testes
        run: dotnet test ./calculadora.teste/bin/Release/net8.0/calculadora.teste.dll --logger "trx;LogFileName=test-results.trx"

      # Publica os resultados dos testes
      - name: Publicar resultados dos testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./calculadora.teste/TestResults/*.trx